FROM python:3.10.4-buster

RUN apt -y update
RUN apt -y upgrade

# setting git
RUN apt -y install git
RUN git config --global user.name Shisato
RUN git config --global user.email shisatoyano@gmail.com